### ISSUE TITLE
Enhance get-nf-balance to return a short representation of token ranges

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#10]
`get-nf-balance` currently always returns the expanded version of token ranges.
User of this API would benefit to get back the short version of a range (i.e `{"min": 29, "max": 299}`) to not have to go through many pages to retrieve the token list.

**Comment by AdamSLevy** [comment]
One issue with implementing this with pagination is that the current code directly marshals a Map type into the bytes of the JSON array. So in order to apply pagination to that list I will need to modify the code to allow for a function that generates a slice of interface{} that can hold either the NFTokenID or the NFTokenIDRange types. Then I can slice that according to the requested pagination.

The other issue with this is that I pretty much always have to request ALL tokens from the database regardless of pagination, because the database doesn't know how well the token ranges will compress. So the benefits of pagination for the server are lost. Additionally I can't use the database to specify the order in which tokens are retrieved. I will have to reorder the tokens after requesting them from the database.

For now I am going to implement this but without pagination or the ability to specify order for the 'get-nf-balance' method. I will continue to return the expanded list from the 'get-nf-tokens' method for now until I get the above mentioned functions implemented/refactored so that I can paginate compressed token ranges.

**Comment by drkatz** [comment]
I'm concerned over the performance hit that this will cause for NF tokens with large circulating supplies based on your description @AdamSLevy, as this could open us up to read based ddos (off Factom, no EC cost) Would it be possible as a compromise to compress the token ranges returned from the page instead of all tokens in the balance? @PaulBernier Currently the `page` and `limit` params are unbounded so it's possible to get quite large slices of compressed token ranges for a `get-nf-balance` or `get-nf-tokens`

**Comment by AdamSLevy** [comment]
Sure. If that's an acceptable approach to pagination then it's no problem. If you ask for a page of the first 1000 tokens and they are contiguous you'll get 0-999 compressed as a single min/max json.

Also I have added a max limit of 1000 at this point.

**Comment by AdamSLevy** [comment]
Previous commit have resolved this issue.
