### ISSUE TITLE
Add API endpoint to list all tokens for an address

### ISSUE THREAD

**Issue by Emyrk** [Factom-Asset-Tokens/fatd#19]
It would be helpful to have an API call that lists all tokens associated with an address. I am thinking about this when considering FAT integration into the TFA explorer. I want to be able, given an FCT address, see all the tokens that it holds. It would also be beneficial to include 0 balances that were once not 0.

This is a quicker process than querying a balance for each possible token on an address. 

The API params should just be an FCT address
The result should include the balance, the token name, and chainid of each token the owner holds. In the case of an `nf` token, the balance field might not be appropriate?

**Comment by AdamSLevy** [comment]
I have wanted to improve the get-balance endpoint as well. 

Certainly the current method is inefficient unless you know ahead of time what token chain you are interested in exactly.

> given an FCT address, see all the tokens that it holds

This can be pretty easily implemented by simply querying against all issued token chain databases. This can be done with existing functions in `db/db.go` in fatd. There is a `db.GetBalance` function that is already used by the "get-balance" method func and there is an example of iterating through issued chains in the "get-daemon-tokens" method func. 

>  It would also be beneficial to include 0 balances that were once not 0.

This is possible but might require modifying the`db.GetBalance` function to distinguish between a 0 due to a lookup failure vs 0 because the address has been inserted into the db.

**Comment by Emyrk** [comment]
@AdamSLevy Is this something that can be added to the daemon in the near future? This is what I need to integrate it into our explorer without having to create my own intermediate database.

**Comment by AdamSLevy** [comment]
Within the next couple weeks.

**Comment by AdamSLevy** [comment]
@Emyrk This is now implemented on develop. will be in next minor release.
