### ISSUE TITLE
Add a Makefile that sets version, commit, build date/time for all builds

### ISSUE THREAD

**Issue by AdamSLevy** [Factom-Asset-Tokens/fatd#4]
Every build should have Version, Commit, and build date/time added to the build. 

We can use the following build flags for this:

```
go build -ldflags "-X flag.Commit=$COMMIT flag.Version=$VERSION flag.BuildDate=$(date)"
```

The COMMIT and VERSION variables can be populated by parsing `git` calls. The commit string should indicate whether there were uncommitted changes that were part of the build. A "+" after the commit can be used to indicate that.

These variables then need to be made available to the user using the `fatd` RPC method "get-daemon-properties" and be available using a command like `fat-cli version`.

**Comment by drkatz** [comment]
Awesome, this will be very useful for version compatibility checking in fat-js. 

One useful feature would be to have the fatd version/commit as a header set by the server in each request. That way concerned clients don't need to worry about using the request content itself to judge compatibility, since the content itself may be incompatible with whoever's requesting it. Do you think this is too paranoid?

**Comment by AdamSLevy** [comment]
Good idea.
