### ISSUE TITLE
Get multiple balances with both acknowledged and saved balances

### ISSUE THREAD

**Issue by PaulBernier** [Factom-Asset-Tokens/fatd#8]
Have an API similar to factomd [`multiple-fct-balances`](https://docs.factom.com/api#multiple-fct-balances)
that would return the temporary balance of an address (acknowledged balance vs saved).

### Motivation

This is very useful for the end user to have the temporary balance of an address before the block is saved. That allows all UIs to be "reactive" to transactions, otherwise having to wait up to 10 minutes to see what has happened is not a good user experience.

How it would work I think would be for fatd to poll the pending entries, filter any FAT transactions and apply those on top of the saved state.

**Comment by drkatz** [comment]
@PaulBernier How do you envision this fitting in with other API calls that use unconfirmed data? Using unconfirmed balances/txs of addresses is very useful many extant calls, not just this purpose built one:

- `get-balance` (single address version of above)
- `get-nf-balance`
- `get-transaction`
- `get-stats` (circ. supply, burned, last tx timestamp which would otherwise be 0-10 mins off, etc)

Personally I would prefer either a fatd startup flag or param you could submit with your RPC request for those methods.

**Comment by AdamSLevy** [comment]
Why not just always return both?

**Comment by drkatz** [comment]
@AdamSLevy Just returning both mutates and clutters the responses a bunch, if I'm taking your meaning correctly. For example, there would have to be `confirmed*` and `unconfirmed*` versions of many fields in `get-stats`, `get-balance` would no longer return an integer :cry: `get-nf-balance` would actually return 2 arrays(?!?). Thoughts?

**Comment by AdamSLevy** [comment]
Good point.

So how about an optional request parameter as you suggested?

**Comment by drkatz** [comment]
@AdamSLevy That would be just fine :+1:

**Comment by AdamSLevy** [comment]
The "includepending" param can be used to request pending balances
